server:
  port: 8082

spring:
  application:
    name: nacos-demo # 注册到 Nacos 的服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos 服务器地址
        # namespace: public           # 命名空间，默认是 public
        group: DEFAULT_GROUP        # 分组，默认是 DEFAULT_GROUP
      config:
        server-addr: localhost:8848 # Nacos 服务器地址
        file-extension: yaml        # 指定配置文件类型，默认为 properties
        group: DEFAULT_GROUP
  config:
      import:
        - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics  # 暴露哪些端点，写 "*" 则是全部
